import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import TelegramWebAppProvider from "@/providers/telegram-webapp-provider";
import Footer from "@/components/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <TelegramWebAppProvider>
          <main className="min-h-screen flex flex-col justify-between ">
            {children}
            <Footer />
          </main>
        </TelegramWebAppProvider>
      </body>
    </html>
  );
}
